name: build, test, and publish

on:
  workflow_call:
    inputs:
      should-package:
        type: boolean
        default: false
      should-run:
        type: string
        default: 'true'

jobs:
  build-test-publish:
    if: inputs.should-run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # required for MinVer
          persist-credentials: false

      - name: setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: |
            src/Directory.Packages.props
            packages/*.nupkg

      - name: build solution
        run: dotnet build Spillgebees.Transmodel.slnx --configuration Release

      - name: test projects
        run: dotnet test --solution Spillgebees.Transmodel.slnx --configuration Release --no-build --verbosity normal

      - name: package NuGet packages
        if: inputs.should-package
        run: |
          dotnet pack src/netex/Spillgebees.NeTEx.Models.V1_2/Spillgebees.NeTEx.Models.V1_2.csproj --configuration Release --no-build --output package
          dotnet pack src/netex/Spillgebees.NeTEx.Models.V1_2_2/Spillgebees.NeTEx.Models.V1_2_2.csproj --configuration Release --no-build --output package
          dotnet pack src/netex/Spillgebees.NeTEx.Models.V1_2_3/Spillgebees.NeTEx.Models.V1_2_3.csproj --configuration Release --no-build --output package
          dotnet pack src/netex/Spillgebees.NeTEx.Models.V1_3_0/Spillgebees.NeTEx.Models.V1_3_0.csproj --configuration Release --no-build --output package
          dotnet pack src/netex/Spillgebees.NeTEx.Models.V1_3_1/Spillgebees.NeTEx.Models.V1_3_1.csproj --configuration Release --no-build --output package
          dotnet pack src/netex/Spillgebees.NeTEx.Models.V1_3_2/Spillgebees.NeTEx.Models.V1_3_2.csproj --configuration Release --no-build --output package
          dotnet pack src/netex/Spillgebees.NeTEx.Models.V2_0_0/Spillgebees.NeTEx.Models.V2_0_0.csproj --configuration Release --no-build --output package
          dotnet pack src/netex/Spillgebees.NeTEx.Models/Spillgebees.NeTEx.Models.csproj --configuration Release --no-build --output package
          dotnet pack src/siri/Spillgebees.SIRI.Models.V2_1/Spillgebees.SIRI.Models.V2_1.csproj --configuration Release --no-build --output package
          dotnet pack src/siri/Spillgebees.SIRI.Models.V2_2/Spillgebees.SIRI.Models.V2_2.csproj --configuration Release --no-build --output package
          dotnet pack src/siri/Spillgebees.SIRI.Models.V2_2_1/Spillgebees.SIRI.Models.V2_2_1.csproj --configuration Release --no-build --output package
          dotnet pack src/siri/Spillgebees.SIRI.Models.V2_3/Spillgebees.SIRI.Models.V2_3.csproj --configuration Release --no-build --output package
          dotnet pack src/siri/Spillgebees.SIRI.Models/Spillgebees.SIRI.Models.csproj --configuration Release --no-build --output package
          dotnet pack src/generator/Spillgebees.Transmodel.Generator/Spillgebees.Transmodel.Generator.csproj --configuration Release --no-build --output package

      - name: upload artifacts
        if: inputs.should-package
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: artifacts
          if-no-files-found: error
          retention-days: 1
          path: package/*.nupkg
